module.exports = [
    {
      id: 1,
      title: "Luxury Beachfront Villa",
      location: "Malibu, California",
      type: "Villa",
      category: "Luxury",
      amenities: ["Pool", "Wi-Fi", "Parking", "Beach Access"],
      guests: 6,
      bedrooms: 3,
      bathrooms: 2,
      pricePerNight: 500,
      images: ["https://picsum.photos/600/400?random=1"]
    },
    {
      id: 2,
      title: "Cozy Mountain Cabin",
      location: "Aspen, Colorado",
      type: "Cabin",
      category: "Nature",
      amenities: ["Fireplace", "Wi-Fi", "Mountain View"],
      guests: 4,
      bedrooms: 2,
      bathrooms: 1,
      pricePerNight: 300,
      images: ["https://picsum.photos/600/400?random=2"]
    },
    {
      id: 3,
      title: "Modern City Apartment",
      location: "New York, New York",
      type: "Apartment",
      category: "Urban",
      amenities: ["Wi-Fi", "Elevator", "Parking"],
      guests: 2,
      bedrooms: 1,
      bathrooms: 1,
      pricePerNight: 200,
      images: ["https://picsum.photos/600/400?random=3"]
    },
    {
      id: 4,
      title: "Luxury Beach Resort",
      location: "Miami, Florida",
      type: "Resort",
      category: "Luxury",
      amenities: ["Pool", "Wi-Fi", "Restaurant", "Spa"],
      guests: 8,
      bedrooms: 4,
      bathrooms: 3,
      pricePerNight: 600,
      images: ["https://picsum.photos/600/400?random=4"]
    },
    {
      id: 5,
      title: "Rustic Forest Cabin",
      location: "Jackson Hole, Wyoming",
      type: "Cabin",
      category: "Nature",
      amenities: ["Fireplace", "Mountain View", "Wi-Fi"],
      guests: 6,
      bedrooms: 3,
      bathrooms: 2,
      pricePerNight: 350,
      images: ["https://picsum.photos/600/400?random=5"]
    },
    {
      id: 6,
      title: "Cozy Downtown Loft",
      location: "Chicago, Illinois",
      type: "Loft",
      category: "Urban",
      amenities: ["Wi-Fi", "Elevator", "Parking"],
      guests: 3,
      bedrooms: 1,
      bathrooms: 1,
      pricePerNight: 250,
      images: ["https://picsum.photos/600/400?random=6"]
    },
    {
      id: 7,
      title: "Sleek Downtown Condo",
      location: "Los Angeles, California",
      type: "Condo",
      category: "Urban",
      amenities: ["Wi-Fi", "Parking", "Elevator"],
      guests: 4,
      bedrooms: 2,
      bathrooms: 1,
      pricePerNight: 280,
      images: ["https://picsum.photos/600/400?random=7"]
    },
    {
      id: 8,
      title: "Charming Countryside Cottage",
      location: "Napa Valley, California",
      type: "Cottage",
      category: "Countryside",
      amenities: ["Wi-Fi", "Garden", "Pet-Friendly"],
      guests: 5,
      bedrooms: 2,
      bathrooms: 2,
      pricePerNight: 220,
      images: ["https://picsum.photos/600/400?random=8"]
    },
    {
      id: 9,
      title: "Luxe Ski Chalet",
      location: "Vail, Colorado",
      type: "Chalet",
      category: "Luxury",
      amenities: ["Hot Tub", "Fireplace", "Ski-In/Ski-Out"],
      guests: 10,
      bedrooms: 5,
      bathrooms: 4,
      pricePerNight: 1000,
      images: ["https://picsum.photos/600/400?random=9"]
    },
    {
      id: 10,
      title: "Beachside Villa with Pool",
      location: "Hawaii, USA",
      type: "Villa",
      category: "Luxury",
      amenities: ["Pool", "Beach Access", "Wi-Fi", "Air Conditioning"],
      guests: 8,
      bedrooms: 4,
      bathrooms: 3,
      pricePerNight: 700,
      images: ["https://picsum.photos/600/400?random=10"]
    },
    {
      id: 11,
      title: "Urban Penthouse",
      location: "San Francisco, California",
      type: "Penthouse",
      category: "Urban",
      amenities: ["Wi-Fi", "Elevator", "City View"],
      guests: 4,
      bedrooms: 2,
      bathrooms: 2,
      pricePerNight: 450,
      images: ["https://picsum.photos/600/400?random=11"]
    },
    {
      id: 12,
      title: "Mountain View Lodge",
      location: "Banff, Canada",
      type: "Lodge",
      category: "Nature",
      amenities: ["Wi-Fi", "Mountain View", "Hot Tub"],
      guests: 6,
      bedrooms: 3,
      bathrooms: 2,
      pricePerNight: 400,
      images: ["https://picsum.photos/600/400?random=12"]
    },
    {
      id: 13,
      title: "Eco-Friendly Bungalow",
      location: "Costa Rica",
      type: "Bungalow",
      category: "Eco",
      amenities: ["Solar Energy", "Wi-Fi", "Private Garden"],
      guests: 4,
      bedrooms: 2,
      bathrooms: 1,
      pricePerNight: 250,
      images: ["https://picsum.photos/600/400?random=13"]
    },
    {
      id: 14,
      title: "Minimalist Studio",
      location: "Austin, Texas",
      type: "Studio",
      category: "Urban",
      amenities: ["Wi-Fi", "Parking", "Smart TV"],
      guests: 2,
      bedrooms: 1,
      bathrooms: 1,
      pricePerNight: 150,
      images: ["https://picsum.photos/600/400?random=14"]
    },
    {
      id: 15,
      title: "Chic City Penthouse",
      location: "Paris, France",
      type: "Penthouse",
      category: "Urban",
      amenities: ["Wi-Fi", "Elevator", "City View"],
      guests: 5,
      bedrooms: 3,
      bathrooms: 2,
      pricePerNight: 550,
      images: ["https://picsum.photos/600/400?random=15"]
    },
    {
      id: 16,
      title: "Secluded Oceanfront Cabin",
      location: "Maui, Hawaii",
      type: "Cabin",
      category: "Nature",
      amenities: ["Private Beach", "Wi-Fi", "Ocean View"],
      guests: 4,
      bedrooms: 2,
      bathrooms: 2,
      pricePerNight: 400,
      images: ["https://picsum.photos/600/400?random=16"]
    },
    {
      id: 17,
      title: "Mountain Retreat Chalet",
      location: "Whistler, Canada",
      type: "Chalet",
      category: "Nature",
      amenities: ["Fireplace", "Hot Tub", "Mountain View"],
      guests: 8,
      bedrooms: 4,
      bathrooms: 3,
      pricePerNight: 600,
      images: ["https://picsum.photos/600/400?random=17"]
    },
    {
      id: 18,
      title: "Luxury Ski Lodge",
      location: "Aspen, Colorado",
      type: "Lodge",
      category: "Luxury",
      amenities: ["Fireplace", "Ski-in/Ski-out", "Hot Tub"],
      guests: 10,
      bedrooms: 5,
      bathrooms: 4,
      pricePerNight: 850,
      images: ["https://picsum.photos/600/400?random=18"]
    },
    {
      id: 19,
      title: "Private Desert Oasis",
      location: "Sedona, Arizona",
      type: "Villa",
      category: "Luxury",
      amenities: ["Pool", "Desert View", "Wi-Fi"],
      guests: 8,
      bedrooms: 4,
      bathrooms: 3,
      pricePerNight: 700,
      images: ["https://picsum.photos/600/400?random=19"]
    },
    {
      id: 20,
      title: "Historic Manor House",
      location: "New Orleans, Louisiana",
      type: "Mansion",
      category: "Historic",
      amenities: ["Wi-Fi", "Fireplace", "Historic Charm"],
      guests: 12,
      bedrooms: 6,
      bathrooms: 5,
      pricePerNight: 1200,
      images: ["https://picsum.photos/600/400?random=20"]
    }
  ];
  