const listingsData = [
    {
      id: 1,
      image: 'https://picsum.photos/600/400?random=1',
      title: "Apartment in Lahore",
      type: 'Entire home',
      guests: 4,
      bedrooms: 2,
      bathrooms: 1,
      price: 77,
      status: 'Booked',
      category: 'Luxury',
      rating: 4.5,
    },
    {
      id: 2,
      image: 'https://picsum.photos/600/400?random=2',
      title: 'Condo in Lahore',
      type: 'Private room',
      guests: 3,
      bedrooms: 1,
      bathrooms: 1,
      price: 50,
      status: 'Available',
      category: 'Family',
      rating: 5,
    },
    {
      id: 3,
      image: 'https://picsum.photos/600/400?random=3',
      title: 'Home in Lahore',
      type: 'Entire home',
      guests: 5,
      bedrooms: 3,
      bathrooms: 2,
      price: 100,
      status: 'Booked',
      category: 'Luxury',
      rating: 3.5,
    },
    {
      id: 4,
      image: 'https://picsum.photos/600/400?random=4',
      title: 'Place to stay in Islamabad',
      type: 'Private room',
      guests: 2,
      bedrooms: 1,
      bathrooms: 1,
      price: 77,
      status: 'Available',
      category: 'Entertainment',
      rating: 4,
    },
    {
      id: 5,
      image: 'https://picsum.photos/600/400?random=5',
      title: 'Modern Villa with Pool',
      type: 'Entire home',
      guests: 6,
      bedrooms: 4,
      bathrooms: 3,
      price: 300,
      status: 'Available',
      category: 'Luxury',
      rating: 4.8,
    },
    {
      id: 6,
      image: 'https://picsum.photos/600/400?random=6',
      title: 'Beach House Escape',
      type: 'Entire home',
      guests: 8,
      bedrooms: 5,
      bathrooms: 4,
      price: 500,
      status: 'Booked',
      category: 'Beachfront',
      rating: 4.9,
    },
    {
      id:7,
      image: 'https://picsum.photos/600/400?random=7',
      title: 'Woods House',
      type: 'Entire home',
      guests: 5,
      bedrooms: 3,
      bathrooms: 3,
      price: 420,
      status: 'Booked',
      category: 'Beachfront',
      rating: 4.7,
    },
    {
      id: 8,
      image: 'https://picsum.photos/600/400?random=8',
      title: 'Beach Apartment',
      type: 'Entire Apartment',
      guests: 6,
      bedrooms: 4,
      bathrooms: 4,
      price: 530,
      status: 'Booked',
      category: 'Beachfront',
      rating: 4.9,
    },
    {
      id: 9,
      image: 'https://picsum.photos/600/400?random=9',
      title: 'Mountain Cabin',
      type: 'Entire cabin',
      guests: 4,
      bedrooms: 2,
      bathrooms: 2,
      price: 150,
      status: 'Available',
      category: 'Adventure',
      rating: 4.6,
    },
    {
      id: 10,
      image: 'https://picsum.photos/600/400?random=10',
      title: 'Penthouse in Karachi',
      type: 'Entire home',
      guests: 10,
      bedrooms: 6,
      bathrooms: 5,
      price: 800,
      status: 'Booked',
      category: 'Luxury',
      rating: 4.9,
    },
    {
      id: 11,
      image: 'https://picsum.photos/600/400?random=11',
      title: 'Charming Bungalow in Islamabad',
      type: 'Entire home',
      guests: 3,
      bedrooms: 1,
      bathrooms: 1,
      price: 200,
      status: 'Available',
      category: 'Family',
      rating: 4.4,
    },
    {
      id: 12,
      image: 'https://picsum.photos/600/400?random=12',
      title: 'Studio Apartment in Rawalpindi',
      type: 'Private room',
      guests: 2,
      bedrooms: 1,
      bathrooms: 1,
      price: 75,
      status: 'Available',
      category: 'Budget',
      rating: 3.8,
    },
    {
      id: 13,
      image: 'https://picsum.photos/600/400?random=13',
      title: 'Eco-Friendly Villa',
      type: 'Entire home',
      guests: 5,
      bedrooms: 3,
      bathrooms: 3,
      price: 350,
      status: 'Booked',
      category: 'Luxury',
      rating: 4.7,
    },
    {
      id: 14,
      image: 'https://picsum.photos/600/400?random=14',
      title: 'Cozy Apartment in Murree',
      type: 'Private room',
      guests: 2,
      bedrooms: 1,
      bathrooms: 1,
      price: 120,
      status: 'Available',
      category: 'Mountain',
      rating: 4.5,
    },
    {
      id: 15,
      image: 'https://picsum.photos/600/400?random=15',
      title: 'Luxurious Mansion in Multan',
      type: 'Entire home',
      guests: 12,
      bedrooms: 8,
      bathrooms: 6,
      price: 1000,
      status: 'Booked',
      category: 'Luxury',
      rating: 4.9,
    },
    {
      id: 16,
      image: 'https://picsum.photos/600/400?random=16',
      title: 'Lakefront Cottage',
      type: 'Entire home',
      guests: 7,
      bedrooms: 4,
      bathrooms: 3,
      price: 450,
      status: 'Available',
      category: 'Waterfront',
      rating: 4.8,
    },
    {
      id: 17,
      image: 'https://picsum.photos/600/400?random=17',
      title: 'Traditional House in Bahawalpur',
      type: 'Entire home',
      guests: 6,
      bedrooms: 4,
      bathrooms: 2,
      price: 300,
      status: 'Available',
      category: 'Cultural',
      rating: 4.6,
    },
    {
      id: 18,
      image: 'https://picsum.photos/600/400?random=18',
      title: 'Stylish Loft in Islamabad',
      type: 'Private room',
      guests: 3,
      bedrooms: 1,
      bathrooms: 1,
      price: 180,
      status: 'Booked',
      category: 'Luxury',
      rating: 4.7,
    },
    {
      id: 19,
      image: 'https://picsum.photos/600/400?random=19',
      title: 'Hilltop Retreat in Swat',
      type: 'Entire cabin',
      guests: 4,
      bedrooms: 2,
      bathrooms: 1,
      price: 250,
      status: 'Available',
      category: 'Adventure',
      rating: 4.6,
    },
    {
      id: 20,
      image: 'https://picsum.photos/600/400?random=20',
      title: 'Modern Apartment in Peshawar',
      type: 'Private room',
      guests: 2,
      bedrooms: 1,
      bathrooms: 1,
      price: 90,
      status: 'Booked',
      category: 'City',
      rating: 4.3,
    }
    
  ];
  
  export default listingsData;
  