const listingsData = [
    {
      id: 1,
      image: 'https://picsum.photos/600/400?random=1',
      title: "Stay in Prince's Purple Rain house",
      type: 'Entire home',
      guests: 4,
      bedrooms: 2,
      bathrooms: 1,
      price: 77,
      status: 'Booked',
      category: 'Luxury',
      rating: 4.5,
    },
    {
      id: 2,
      image: 'https://picsum.photos/600/400?random=2',
      title: 'Sleepover at Polly Pocket’s Compact',
      type: 'Private room',
      guests: 3,
      bedrooms: 1,
      bathrooms: 1,
      price: 50,
      status: 'Available',
      category: 'Family',
      rating: 5,
    },
    {
      id: 3,
      image: 'https://picsum.photos/600/400?random=3',
      title: 'Playdate at Polly Pocket’s Compact',
      type: 'Entire home',
      guests: 5,
      bedrooms: 3,
      bathrooms: 2,
      price: 100,
      status: 'Booked',
      category: 'Luxury',
      rating: 3.5,
    },
    {
      id: 4,
      image: 'https://picsum.photos/600/400?random=4',
      title: 'Join the Living Room Session with Doja Cat',
      type: 'Private room',
      guests: 2,
      bedrooms: 1,
      bathrooms: 1,
      price: 77,
      status: 'Available',
      category: 'Entertainment',
      rating: 4,
    },
    {
      id: 5,
      image: 'https://picsum.photos/600/400?random=5',
      title: 'Modern Villa with Pool',
      type: 'Entire home',
      guests: 6,
      bedrooms: 4,
      bathrooms: 3,
      price: 300,
      status: 'Available',
      category: 'Luxury',
      rating: 4.8,
    },
    {
      id: 6,
      image: 'https://picsum.photos/600/400?random=6',
      title: 'Beach House Escape',
      type: 'Entire home',
      guests: 8,
      bedrooms: 5,
      bathrooms: 4,
      price: 500,
      status: 'Booked',
      category: 'Beachfront',
      rating: 4.9,
    },
    {
      id:76,
      image: 'https://picsum.photos/600/400?random=7',
      title: 'Woods House',
      type: 'Entire home',
      guests: 5,
      bedrooms: 3,
      bathrooms: 3,
      price: 420,
      status: 'Booked',
      category: 'Beachfront',
      rating: 4.7,
    },
    {
      id: 8,
      image: 'https://picsum.photos/600/400?random=8',
      title: 'Beach Apartment',
      type: 'Entire Apartment',
      guests: 6,
      bedrooms: 4,
      bathrooms: 4,
      price: 530,
      status: 'Booked',
      category: 'Beachfront',
      rating: 4.9,
    },
  ];
  
  export default listingsData;
  